### ISSUE TITLE
wrong architecture error when I tried to run "sloth examples/example1_labels.json"

### ISSUE THREAD

**Issue by molian6** [cvhciKIT/sloth#102]
`Traceback (most recent call last):
  File "/Users/molian/anaconda/bin/sloth", line 5, in <module>
    from PyQt4.QtGui import QApplication
ImportError: dlopen(/Users/molian/anaconda/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): no suitable image found.  Did find:
    /Users/molian/anaconda/lib/python2.7/site-packages/PyQt4/QtGui.so: mach-o, but wrong architecture`

I opened python and tried "from PyQt4.QtGui import QApplication", there was no error message. I only got this wrong architecture error when I run sloth.
I was using anaconda python2.7 and have installed PIL, Sphinx and PyQt with anaconda.

**Comment by nilsonholger** [comment]
I think anaconda is causing problems here, I even think I have seen this weird behavior before, maybe even in another issue. You seem to be on OS X, if you use `homebrew`, you could just do a `brew install pyqt` and try that, it works fine for me. Or maybe manually try pointing your `$PYTHONPATH` environment variable to that anaconda install...but that wrong architecture message also hints to other problems on your installation. Sorry that I am of no further help, but it is impossible for me to reproduce your setup, except for screwing up my own development machine.

**Comment by nilsonholger** [comment]
No answer, so I'm officially logging this as anaconda's problem now.
