### ISSUE TITLE
Sloth does not go to previously opened file path when File|Open selected.

### ISSUE THREAD

**Issue by isaacgerg** [cvhciKIT/sloth#104]

**Comment by nilsonholger** [comment]
Well, it does so OSX when doing an "Open existing annotation file", but it doesn't for the "Add an image" button (it ALWAYS starts at the current running directory), so I really can't reproduce your problem. Also, as this functionality seems to be OS dependent, I would not want to include such a mechanism "per OS", that would make the code quite messy. So sorry, but that's a "can't/won't fix"!
