### ISSUE TITLE
Updated annotations table display

### ISSUE THREAD

**Issue by isaacgerg** [cvhciKIT/sloth#105]
Annotations table display should show:
1. the current show image in the main window should be highlighted in the annotations list.  Currently, you can easily get into a state where you can't see what file you have selected unless you match the filename on the main window with the list of annotations.  This is very cumbersome for large datasets.
2. Annotations should indicate if a file has been seen or not by the user.  This way, a user can load hundreds of images, begin labeling them, save the json file, exit Sloth, and then open sloth at a later time and pick up where he left with the labeling task.

**Comment by nilsonholger** [comment]
Fixed by Pull Request #106! Many thx to @isaacgerg!
