### ISSUE TITLE
data labelling tool for automotive

### ISSUE THREAD

**Issue by devanandd** [cvhciKIT/sloth#108]
what is the time required for labelling an object in one single frame by using data labelling tool in both methods (manual and semi-automatic labeling)

**Comment by nilsonholger** [comment]
Uhmmm...so WHAT EXACTLY seems to be the question here? Your required time to label just about anything will greatly depend upon:
- image size
- number of objects in image
- your mouse speed
- your click rate
- your motor skills
- your ability to pre-process/create automatic labels
- and yes, of course, your used tools.

Sorry, but won't-fix!!!
