### ISSUE TITLE
Handle uppercase file extensions (.JPG, .PNG, ...)

### ISSUE THREAD

**Issue by nilsonholger** [cvhciKIT/sloth#109]
Trying to load an image file with an uppercase extension leads to a failure (as described by @RockyCD in #107)

**Comment by terriyu** [comment]
I don't know if this is related, but I couldn't open images with the extension ".tiff"

I fixed this by making the following change in `sloth/gui/labeltool.py` :

`-   image_types = [ '*.jpg', '*.bmp', '*.png', '*.pgm', '*.ppm', '*.ppm', '*.tif', '*.gif' ]`
`+  image_types = [ '*.jpg', '*.bmp', '*.png', '*.pgm', '*.ppm', '*.ppm', '*.tif', '*.tiff', '*.gif' ]`

**Comment by nilsonholger** [comment]
@terriyu Just added '*.tiff' to the list of image types in commit de636a1, thx for the report, didn't even get noticed so far.
