### ISSUE TITLE
unable to annotate videos

### ISSUE THREAD

**Issue by bmabey** [cvhciKIT/sloth#112]
I'm trying to figure out how to use Sloth for videos (I got it working great for images). I don't see how to add a video via the GUI and when I try to add one directly in the JSON with `    {"class": "video", "filename": "my_video.mp4"}` I see the video listed in Sloth but when I click on it the following error occurs:

```python
/../anaconda/lib/python2.7/site-packages/sloth/gui/labeltool.py:132: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if img == None:
Traceback (most recent call last):
  File "/../anaconda/lib/python2.7/site-packages/sloth/core/labeltool.py", line 334, in setCurrentImage
    raise RuntimeError("Tried to set current image to item that has no Image or Frame as parent!")
RuntimeError: Tried to set current image to item that has no Image or Frame as parent!
```
Any tips or pointers on how to annotate videos with Sloth? Do I need to update my config?

Thanks for Sloth, it has been awesome so far with images.

**Comment by bmabey** [comment]
I tried appending the video file using the CLI and saw similar behaviour as above so I believe the problem is that video support has a bug. I'm using python 2.7 with Anaconda on OSx.

**Comment by nilsonholger** [comment]
Please see #89 and #86. Currently, there is no working video support with sloth outside our research group. I have personally never used it with videos, I've **always** preferred to separate the video into individual images and work on those instead. Maybe that could be a resolution for the new year, get video support working again by using an open source video library with sloth. Sorry, but that means I currently can't/won't fix this behaviour right now, but I'm happy to take any pull requests for it.
