### ISSUE TITLE
Bug when dragging zoomed-in items

### ISSUE THREAD

**Issue by csaftoiu** [cvhciKIT/sloth#113]
It leaves a trail:

https://www.youtube.com/watch?v=gZA66AvuaDs&feature=youtu.be

Default config and everything.

**Comment by nilsonholger** [comment]
I could not confirm that problem, what platform are you on and are you using the latest sloth version? My point label actually looks quite different from yours (thinner unsegmented lines). For me, there are no artifacts left over in the image. Just guessing wildely here, but ost likely this is due a bug in the PyQt4.QtGui version you are using.

**Comment by nilsonholger** [comment]
Closing this issue as there has been no confirmation and no further replies...
