### ISSUE TITLE
How can I make the file translate to the xml file that I need?

### ISSUE THREAD

**Issue by MU001999** [cvhciKIT/sloth#115]
It will be like the content of the yaml file when I save as xml file.
Please help me. @neingeist @mika-fischer @wassname

**Comment by nilsonholger** [comment]
Uhmmm...I'm not sure I correctly understand your question, but afaik sloth does NOT support saving to XMS files. Google for "YAML to XML converter" or similar and you will most likely find something that suits your needs!

**Comment by tgehrig** [comment]
You have to implement a container interface which writes the annotations as xml. As far as I know, sloth does not have a container which writes out xml out of the box. Just have a look at [sloth/annotations/container.py](https://github.com/cvhciKIT/sloth/blob/master/sloth/annotations/container.py) there are multiple container implementations use one as a basis and reimplement the `serializeToFile()` function to output the xml file.

**Comment by MU001999** [comment]
@tgehrig @nilsonholger Thanks you two. I have solved this problem by another way. Uhmmm...Actually, I just implement a parser for the json to load the file in my machine learning model. Thanks very much.
