### ISSUE TITLE
Unable to run - ImportError: libQtMultimedia.so.4

### ISSUE THREAD

**Issue by arnitkun** [cvhciKIT/sloth#163]
Ubuntu 16, Anaconda python 2.7

running `$ sloth` gives - 

```
from PyQt4.QtGui import QApplication
ImportError: libQtMultimedia.so.4: cannot open shared object file: No such file or directory
```

- I have installed pyqt4 via anaconda.
- I have installed libqt4-dev and libqt4-multimedia : No success

**Comment by jimbasquiat** [comment]
Any help on this issue? (having the same problem)

**Comment by arnitkun** [comment]
nope sorry. Also apologize for late reply.

**Comment by AyanKumarBhunia** [comment]
solution?

**Comment by andres-fr** [comment]
In my case (Ubuntu17, Anaconda with Python 2.7), I had installed Qt4 via `conda install -c terradue pyqt4`. Removing that package and installing via `conda install pyqt=4` as suggested [here](https://stackoverflow.com/a/40920535) did the trick. HTH!
