### ISSUE TITLE
Converting annotations to YOLO format

### ISSUE THREAD

**Issue by cemysf** [cvhciKIT/sloth#167]
I need to label some data for the YOLO, which requires a quite different annotation format.

Anyone tried using these json annotations with YOLO? I know I need to write a script to convert it, just wanted to ask here first, maybe you guys already have one

**Comment by adouwitti** [comment]
@cemysf hi , refer to this link : https://github.com/ssaru/convert2Yolo  , i think that it will help you

**Comment by adouwitti** [comment]
if you still need annotations-yolo_format converter .
