### ISSUE TITLE
Error trying to save file: 'No container registered for ... ' 

### ISSUE THREAD

**Issue by nimrodshn** [cvhciKIT/sloth#93]
While trying to save a new annotation file to folder I got the above messege. Any ideas/fixes?

**Comment by khnaba** [comment]
I run into the same issue. You may not have specified the file extension such as .json or .yaml while saving. Sloth seems to use the file ext to determine container type. Hope it helps.

**Comment by nilsonholger** [comment]
@nimrodshn Yes, this is due to not specifying an extension. I will add a note to fix this.

**Comment by simonhessner** [comment]
I get the same error message using the newest version of sloth when I try to save my annotations without specifying a file extension.
